-d /home/txf/git/TC_RISCV/gowin/TC_RISCV/impl/gwsynthesis/TC_RISCV.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/txf/git/TC_RISCV/gowin/TC_RISCV/src/TC_RISCV.cst
-cfg /home/txf/git/TC_RISCV/gowin/TC_RISCV/impl/pnr/device.cfg
-sdc /home/txf/git/TC_RISCV/gowin/TC_RISCV/src/TC_RISCV.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
